#ifndef COSTFUNCTION_POLICY_MACROS_H_
#define COSTFUNCTION_POLICY_MACROS_H_

#define INHERIT_FIT_POLICY_TYPEDEFS(FROM) \
  INHERIT_FITFUNC_POLICY_TYPEDEFS(FROM); \
  INHERIT_TYPEDEF(FROM,costFunctionType); \
  INHERIT_TYPEDEF(FROM,costFunctionState)

#endif
